name: EAS Dev/Prod OTA & Build

on:
  push:
    branches:
      - dev
      - main
  workflow_dispatch:
    inputs:
      promote_from_branch:
        description: 'Branch to promote from'
        required: false
        default: 'dev'

jobs:
  ota-update:
    runs-on: ubuntu-latest
    if: github.ref_name == 'dev' || github.ref_name == 'main'
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: EAS OTA Update
        run: eas update --branch "${{ github.ref_name }}" --non-interactive --message "OTA update on ${{ github.ref_name }}"

      - name: EAS Production Builds (iOS + Android)
        if: github.ref_name == 'main'
        run: eas workflow:run create-production-builds.yml --non-interactive

  promote-dev-to-main:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Promote dev to main
        run: eas update:promote --from-branch "${{ github.event.inputs.promote_from_branch }}" --to-branch main --non-interactive --message "Promote to main" 