name: EAS Dev/Prod OTA & Build

on:
  push:
    branches:
      - dev
      - main
  workflow_dispatch:
    inputs:
      promote_from_branch:
        description: 'Branch to promote from'
        required: false
        default: 'dev'

jobs:
  ota-update:
    runs-on: ubuntu-latest
    if: github.ref_name == 'dev' || github.ref_name == 'main'
    steps:
      - uses: actions/checkout@v4

      - uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: EAS OTA Update
        run: eas update --branch ${{ github.ref_name }} --non-interactive --message "OTA update (${{ github.ref_name }}): ${{ github.sha }}"

      - name: EAS Build (Android)
        if: github.ref_name == 'main'
        run: eas build --platform android --non-interactive --profile production

      - name: EAS Build (iOS)
        if: github.ref_name == 'main'
        run: eas build --platform ios --non-interactive --profile production

  promote-dev-to-main:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v4

      - uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Promote dev to main
        run: |
          FROM_BRANCH="${{ github.event.inputs.promote_from_branch }}"
          echo "Promoting from $FROM_BRANCH to main..."
          eas update:promote --from-branch "$FROM_BRANCH" --to-branch main --non-interactive --message "Promote $FROM_BRANCH to main: ${{ github.sha }}" 